services:
 postgres:
  container_name: registration-service-postgres
  image: postgres:17.2-alpine3.20
  restart: unless-stopped
  env_file:
    - .env-example
  environment:
    - POSTGRES_DB=${DB_NAME}
    - POSTGRES_USER=${DB_USER}
    - POSTGRES_PASSWORD=${DB_PASSWORD}
  ports:
    - ${DB_PORT_LOCAL}:${DB_PORT_CONTAINER}
  volumes:
    - pg_data:/var/lib/postgresql/data
  networks:
    - postgresql
  healthcheck:
    test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
    interval: 5s
    timeout: 5s
    retries: 10

volumes:
  pg_data:

networks:
  postgresql:
